# bind-mount source dirs for on /blockchain

# cardano-node
d /blockchain/cardano         0755 cardano-node cardano-node -
d /blockchain/cardano/mainnet 0755 cardano-node cardano-node -
d /blockchain/cardano/preprod 0755 cardano-node cardano-node -
d /blockchain/cardano/preview 0755 cardano-node cardano-node -

# cardano-db-sync
d /blockchain/cardano-db-sync         0755 cardano-node cardano-node -
d /blockchain/cardano-db-sync/mainnet 0755 cardano-node cardano-node -
d /blockchain/cardano-db-sync/preprod 0755 cardano-node cardano-node -
d /blockchain/cardano-db-sync/preview 0755 cardano-node cardano-node -
